baseURL = "https://www.empiresmod.com/"
languageCode = "en-us"
title = "Empires"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "Empires"
    languageName = "English"
    weight = 1
  
  [languages.ru]
    title = "Empires"
    languageName = "русский"
    weight = 2